sudo: required
services:
  - docker

before_install:
  - docker build -t suryasindwani/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true suryasindwani/react-test npm test -- --coverage

after_success:
  - docker build -t suryasindwani/multi-client ./client
  - docker build -t suryasindwani/multi-nginx ./nginx
  - docker build -t suryasindwani/multi-server ./server
  - docker build -t suryasindwani/multi-worker ./worker
# Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push suryasindwani/multi-client
  - docker push suryasindwani/multi-nginx
  - docker push suryasindwani/multi-server
  - docker push suryasindwani/multi-worker
